### ISSUE TITLE
ColumnRole

### ISSUE THREAD

**Issue by pymsoft** [connollyst/zkgooglecharts#4]
Hi Sean, 

There still is a problem with the Column Role, which is solely assigned to the last column in the case there will be more than one column in DataTable.
An example:

``` java
DataTable data = new DataTable();
data.addStringColumn("Task", "task");
    data.addNumberColumn("Hours per Day", "hours");
    data.addNumberColumn("Pieces", "pieces");
    data.addColumn(ColumnType.STRING, ColumnRole.TOOLTIP);
    data.addColumn(ColumnType.STRING, ColumnRole.STYLE);
    data.addRow("Work", 6, 5, null, "opacity: 0.2");
    data.addRow("Eat", 5, 4, "Hello world!", "opacity: 0.2");
    data.addRow("Commute", 7, 4, null, "fill-color: #76A7FA");
    data.addRow("Watch TV", 6, 5, "Hello world!", "color: #76A7FA");
    data.addRow("Sleep", new FormattedValue(7, "7.000"), 3, null, "opacity: 0.7");
    System.out.println(data.toJSONString());
    Map<String, Object> hAxis = new HashMap<String, Object>();
    Map<String, Object> vAxis = new HashMap<String, Object>();
    Map<String, Object> animation = new HashMap<String, Object>();
    hAxis.put("title", "Totali annuali");
    hAxis.put("minValue", 0);
    vAxis.put("title", "Valori in €");
    animation.put("duration", 1000);
    animation.put("easing", "out"); // linear, in, out, inAndOut
    animation.put("startup", true);
    org.zkoss.google.charts.ColumnChart chart = new ColumnChart();
    chart.setData(data);
    chart.setTitle("Comparativa annuale");
    chart.setOption("subtitle", "Sotto Titolo");
    chart.setOption("hAxis", hAxis);
    chart.setOption("vAxis", vAxis);    
    chart.setOption("animation", animation);
    chart.setData(data);
    chart.setParent(wchart);
```

**Comment by pymsoft** [comment]
Solved!

The column role must be assigned to each column.

``` java
DataTable data = new DataTable();
    data.addStringColumn("Task", "task");
    data.addNumberColumn("Hours per Day", "hours");
    data.addColumn(ColumnType.STRING, ColumnRole.STYLE);
    data.addNumberColumn("Pieces", "pieces");
    data.addColumn(ColumnType.STRING, ColumnRole.TOOLTIP);
    data.addColumn(ColumnType.STRING, ColumnRole.STYLE);
    data.addRow("Work", 6, "opacity: 0.2", 5, null, "opacity: 0.2");
    data.addRow("Eat", 5, "opacity: 0.2", 4, "Hello world!", "opacity: 0.2");
    data.addRow("Commute", 7,"opacity: 0.2", 4, null, "fill-color: #76A7FA");
    data.addRow("Watch TV", 6,"opacity: 0.2", 5, "Hello world!", "color: #76A7FA");
    data.addRow("Sleep", new FormattedValue(7, "7.000"), "opacity: 0.2", 3, null, "opacity: 0.7");
```

**Comment by connollyst** [comment]
Hey Pedro,

Sorry, I don't fully follow. Can you elaborate on the problem & the solution, it may be a help to others with the same issue later.

Is there anything you'd like changed/fixed in the library?

If everything is good, can you close the ticket?

Thanks,
Sean

**Comment by pymsoft** [comment]
Hi Sean, 

Everything is good with library.

Thank you for your work.

Pedro

**Comment by connollyst** [comment]
Cheers.

**Comment by pymsoft** [comment]
Hi Sean, 

I tried to change the properties of the legend to move it to the top but do not know how to do. Do you have any idea how can I do?

Thank you

Pedro Gonzalez
var data = google.visualization.arrayToDataTable([
        ['Genre', 'Fantasy & Sci Fi', 'Romance', 'Mystery/Crime', 'General',
         'Western', 'Literature', { role: 'annotation' } ],
        ['2010', 10, 24, 20, 32, 18, 5, ''],
        ['2020', 16, 22, 23, 30, 16, 9, ''],
        ['2030', 28, 19, 29, 30, 12, 13, '']
      ]);

```
  var options = {
    width: 600,
    height: 400,
    legend: { position: 'top', maxLines: 3 },
    bar: { groupWidth: '75%' },
    isStacked: true
  };
```

Map<String, Object> legend = new HashMap<String, Object>();
Object[] leg = new Object[1];
String[][] legvals = { {"position", "top" } };
leg[0] = legvals;
legend.put("legend", leg );

org.zkoss.google.charts.ColumnChart chart = new ColumnChart();

chart.setOption("legend", legend);

Il giorno 01 giu 2016, alle ore 20:46, Sean Connolly notifications@github.com ha scritto:

Hey Pedro,

Sorry, I don't fully follow. Can you elaborate on the problem & the solution, it may be a help to others with the same issue later.

Is there anything you'd like changed/fixed in the library?

Thanks,
Sean

**Comment by connollyst** [comment]
Hey Pedro,

Those parameters are passed directly to the client as a JSON serialization. The structure you're building isn't the JSON structure Google Charts expects. Your JSON looks like:

```
legend : {
  legend : [
    [
        [
            "position",
            "top"
        ]
    ]
  ]
}
```

As you show in your `var options` you want

```
legend : {
  position : "top"
}
```

**Comment by pymsoft** [comment]
Hi Sean,

how do I send multiple parameters?

`legend: { position: 'top', maxLines: 3 },`

Best

Pedro

**Comment by connollyst** [comment]
```
Map<String, Object> legend = new HashMap<>();
legend.put("position", "top");
legend.put("maxLines", 3);
chart.setOption("legend", legend);
```

**Comment by pymsoft** [comment]
Thank's

I have to change the project to JRE 1.7 but now works.

Thank you

**Comment by connollyst** [comment]
For JRE 1.6 it would work fine with..

```
Map<String, Object> legend = new HashMap<String, Object>();
```

**Comment by pymsoft** [comment]
/*
        Map<String, Object> legend = new HashMap<String, Object>();
        Object[][] legvals = { {"position", "top" }, {"maxlines", 3} };
        legend.put("legend", legvals );
                chart.setOption("legend", legend);
*/

Now I understand where I was wrong.
Consider that I am self-taught and forget my solid background in Java

Thanks again.

**Comment by connollyst** [comment]
Not a problem, best of luck.
