### ISSUE TITLE
Usage of the onClick event

### ISSUE THREAD

**Issue by remiemalik** [connollyst/zkgooglecharts#5]
Hi,
First of all thank you for this wonderfull addition.
Secondly, we are using the zkgooglecharts. However, we want to incorporate a zk-click event when someone clickes on a part of a chart. I see that there is a method setWidgetListener. However, how is it possible to handle the click event in the zk framework. Is this even possible? Or is this method intended for javascript usage? 

Thanks,

Kind regards ,

Remie

**Comment by connollyst** [comment]
Hey there Remie,

Sorry for the slow response, thanks for the kind words.

Click events are already supported using ZK so you should be able to achieve what you want without any fiddling with JavaScript. From Java you can do something like:

````
chart.addEventListener(GoogleChartEvents.ON_CLICK, new EventListener<Event>() {
    @Override
    public void onEvent(Event event) {
        System.out.println(event.getData());
    }
});
````

This is all supported using listener wiring if that's makes more sense, e.g.:
````
@Listen(GoogleChartEvents.ON_CLICK + " = #myChart")
public void chartClicked(Event event) {
    System.out.println(event.getData());
}
````

Note that [``GoogleChartEvents``](https://github.com/connollyst/zkgooglecharts/blob/master/src/main/java/org/zkoss/google/charts/GoogleChartEvents.java) is a convenience, similar to ZK's [``Events``](https://github.com/zkoss/zk/blob/master/zk/src/org/zkoss/zk/ui/event/Events.java). In fact, most of those Strings are coming directly from ``Events``, though there are some that aren't found in ``Events``, such as the "onReady" and "onAnimationFinish" events that Google Charts provides.

Lastly, just wanted to let you know that ``GoogleChartEvents.ON_SELECT`` might be what you're after too. It maps to [Google Chart's "select" event](https://developers.google.com/chart/interactive/docs/basic_interactivity) which fires when the user clicks a pie slice or something very specific, as opposed to simply clicking anywhere on the chart area.

Let me know if you need any more help.

Cheers,
Sean
